### ISSUE TITLE
Add Scroll Button

### ISSUE THREAD

**Issue by nima-karami** [nima-karami/nima-karami.github.io#1]
Add a scroll button at the end of every section.

**Comment by ahmet-topal** [comment]
Hi, actually i couldn't understand what do you want really. If can you explain it more clearly i might do it. Do you want a button 
which allows you to switch to the section below. Right?

**Comment by nima-karami** [comment]
@ahmet-topal 
Hi. I hope you're doing well.
These comments are actually for me. Trying to keep track of the features I need to add in the future.

I was going to add a button in every section that scrolls down to the next section
For example, there would be a button at the bottom of the "skills" section that would go down to the "projects" section if clicked. 

Similar to the button below:

![image](https://user-images.githubusercontent.com/94768955/169608670-382149be-4d64-401f-b2cd-f136c6ab45d3.png)

**Comment by ahmet-topal** [comment]
Okay. So i am going to do it as soon as possible. I only have one request from you. After solving the problem if you like my solution can you close this issues please? This is my lesson project and that is what my teacher want.

**Comment by nima-karami** [comment]
@ahmet-topal sound good!

**Comment by nima-karami** [comment]
Hi Ahmet,

I hope you're doing well. You don't need to be added to the project to
contribute.
Create a pull request and I will review your changes.

Thank you,
Nima Karami
